---
dependencies:
  - role: download
    file: "{{ downloads.hyperkube }}"
    tags:
      - download
      - hyperkube
      - kubelet
      - network
      - canal
      - calico
      - weave
      - kube-controller-manager
      - kube-scheduler
      - kube-apiserver
      - kube-proxy
      - kubectl

  - role: download
    file: "{{ downloads.pod_infra }}"
    tags:
      - download
      - kubelet

  - role: download
    file: "{{ downloads.install_socat }}"
    when: ansible_os_family in ['CoreOS', 'Container Linux by CoreOS']
    tags:
      - download
      - kubelet

  - role: download
    file: "{{ downloads.kubeadm }}"
    when: kubeadm_enabled
    tags:
      - download
      - kubelet
      - kubeadm

  - role: kubernetes/secrets
    when: not kubeadm_enabled
    tags:
      - k8s-secrets
  - role: download
    file: "{{ downloads.nginx }}"
    tags:
      - download
      - nginx

  - role: download
    file: "{{ downloads.testbox }}"
    tags:
      - download

  - role: download
    file: "{{ downloads.netcheck_server }}"
    when: deploy_netchecker
    tags:
      - download
      - netchecker

  - role: download
    file: "{{ downloads.netcheck_agent }}"
    when: deploy_netchecker
    tags:
      - download
      - netchecker

  - role: download
    file: "{{ downloads.kubedns }}"
    tags:
      - download
      - dnsmasq

  - role: download
    file: "{{ downloads.dnsmasq_nanny }}"
    tags:
      - download
      - dnsmasq

  - role: download
    file: "{{ downloads.dnsmasq_sidecar }}"
    tags:
      - download
      - dnsmasq

  - role: download
    file: "{{ downloads.kubednsautoscaler }}"
    tags:
      - download
      - dnsmasq
